services:
  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - solver
  solver:
    build: ./solver
    ports:
      - "8000:8000"